name:                Partie
version:             0.1.0.0
synopsis:            demonstrating playing simple games using FP
homepage:            https://github.com/CarstenKoenig/Partie#readme
license:             BSD3
author:              Carsten König
maintainer:          Carsten.Koenig@hotmail.de
copyright:           2018 Carsten König
category:            Web, Game
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - mtl
  - containers
  - aeson
  - stm
  - uuid

library:
  source-dirs:        src/lib
  exposed-modules:
    - Test
    - Games.Scotty
  dependencies:
    - scotty

executables:
  Partie:
    source-dirs:      src/app
    main:             Main.hs
    dependencies:
      - Partie
      - scotty
      - wai-middleware-static
  PS-bridge:
    source-dirs:      src/bridge
    main:             Main.hs
    dependencies:
      - Partie
      - purescript-bridge
    
